version: "3"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${DOMAIN_NAME}
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/mail-data:/var/mail
      - ./data/mail-state:/var/mail-state
      - ./data/mail-logs:/var/log/mail
      - ./conf/docker-mailserver:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 34010:5432
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    hostname: roundcube
    volumes:
      - ./data/www:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.${DOMAIN_NAME}
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.${DOMAIN_NAME}
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./conf/ssl:/etc/letsencrypt/live
    restart: always

